services:
  etl_engine:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      # Mapujemy cały folder projektu (z WSL) do /app w kontenerze
      - .:/app
      # Mapujemy dane z GDrive (tylko do odczytu)
      - "/mnt/g/Mój dysk:/app/gdrive_raw:ro"
    environment:
      - PYTHONUNBUFFERED=1
      # KLUCZOWE: Mówimy Pythonowi, że w folderze /app są nasze moduły
      - PYTHONPATH=/app
    # Uruchamiamy main.py bezpośrednio
    command: python /app/src/main.py