FROM python:3.11-slim

WORKDIR /app

# Kopiujemy requirements i instalujemy
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiujemy resztę kodu (na wypadek, gdybyśmy nie używali wolumenów, np. w chmurze)
COPY . .

# Uruchamiamy główny skrypt
CMD ["python", "src/main.py"]