FROM python:3.11-slim

# Instalacja zależności systemowych (potrzebne dla DVC i Google Drive)
RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

# Tworzymy użytkownika o Twoim UID (1000)
# Nadajemy mu nazwę 'developer' (może być dowolna)
RUN useradd -m -u 1000 developer

# Ustawiamy katalog roboczy
WORKDIR /app

# Kopiujemy requirements i instalujemy paczki jako root
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Zmieniamy właściciela folderu /app na naszego użytkownika
RUN chown -R developer:developer /app

# Przełączamy się na użytkownika 'developer'
USER developer

# Kopiujemy resztę kodu
COPY --chown=developer:developer . .

# Domyślna komenda (można ją nadpisać w docker-compose)
CMD ["python", "src/main.py"]